#jugando con swagger

openapi: 3.0.0
info:
  title: API Like Me
  version: 1.0.0
paths:
  /posts:
    get:
      summary: Obtener todos los posts
      responses:
        '200':
          description: Lista de posts
    post:
      summary: Crear un nuevo post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  example: "Nuevo post"
                url:
                  type: string
                  example: "https://example.com"
                descripcion:
                  type: string
                  example: "Descripción del post"
      responses:
        '201':
          description: Post creado exitosamente
